// SPDX-License-Identifier: AGPL-3.0-only
// Copyright © 2026 Jim Collier

package ddl

import (
	"embed"
	"fmt"
	"maps"
	"slices"
	"strings"
	"sync"

	shcl "github.com/jim-collier/shcl/source/go"
)

// schema.shcl states the DDL's vocabulary for shcl's validator. Embedding it
// keeps the one static binary intact and keeps the vocabulary reviewable as a
// plain file rather than buried in Go string literals.
//
//go:embed schema.shcl
var schemaFS embed.FS

// blockDepth is how many levels of nested layout `block:` the schema declares.
// Layout blocks nest recursively, which a closed schema vocabulary cannot
// express, so the paths are generated to a fixed depth instead. A block nested
// deeper than this still parses and renders - only its keys stop being
// validated, reported as unknown fields. Real layouts are two or three deep;
// this leaves generous room.
const blockDepth = 8

// blockKeys are a layout block's own attributes, repeated at every depth.
var blockKeys = map[string]string{
	"table":        "string",
	"type":         "string",
	"parent_field": "string",
	"location":     "string-array",
	"readonly":     "bool",
}

// blockTypes is the closed set of block kinds, kept here beside the generated
// paths rather than in schema.shcl so the two cannot drift apart.
var blockTypes = "form, grid, tree_grid, comments"

var (
	schemaOnce sync.Once
	schemaDocV *shcl.Document
)

// schemaDoc returns the validation schema: the embedded file plus the generated
// recursive block paths. Parsed once - it is immutable, and Validate only reads
// it, so every DDL load shares the one document.
func schemaDoc() *shcl.Document {
	schemaOnce.Do(func() {
		text, err := schemaFS.ReadFile("schema.shcl")
		if err != nil {
			// Embedded at build time, so this cannot fail in a shipped binary;
			// an empty schema degrades to "validate nothing" rather than
			// refusing to open a database over a build problem.
			schemaDocV = shcl.New()
			return
		}
		full := string(text) + generatedBlockSchema()
		schemaDocV = shcl.Parse(full + unwrappedVariants(full))
	})
	return schemaDocV
}

// unwrappedVariants re-emits every entry whose path sits under the database: or
// ui: wrapper, with the wrapper stripped. Those wrappers are organizational, so
// the DDL accepts a section at either depth - the built-in schema and most test
// fixtures write the flat form. Generating the second spelling keeps the one
// hand-written vocabulary in schema.shcl as the single source.
func unwrappedVariants(text string) string {
	var out strings.Builder
	out.WriteString("\n# Generated by schema.go: the same paths without the database:/ui: wrapper.\n")
	lines := strings.Split(text, "\n")
	for i, line := range lines {
		path, ok := schemaEntryPath(line)
		if !ok {
			continue
		}
		flat, ok := stripWrapper(path)
		if !ok {
			continue
		}
		// A path is always safe to quote, and a selector requires it.
		fmt.Fprintf(&out, "field: %q\n", flat)
		for j := i + 1; j < len(lines) && isIndentedLine(lines[j]); j++ {
			out.WriteString(lines[j] + "\n")
		}
	}
	return out.String()
}

// schemaEntryPath pulls the document path out of a `field: <path>` schema line.
func schemaEntryPath(line string) (string, bool) {
	rest, ok := strings.CutPrefix(line, "field:")
	if !ok {
		return "", false // indented constraint, comment, or blank
	}
	path := strings.TrimSpace(rest)
	if unquoted, was := Unquote(path); was {
		path = unquoted
	}
	return path, path != ""
}

// stripWrapper removes a leading database./ui. segment, reporting whether the
// path had one.
func stripWrapper(path string) (string, bool) {
	for _, wrapper := range []string{"database.", "ui."} {
		if flat, ok := strings.CutPrefix(path, wrapper); ok {
			return flat, true
		}
	}
	return path, false
}

// isIndentedLine reports whether a line continues the entry above it.
func isIndentedLine(line string) bool {
	return line != "" && (line[0] == '\t' || line[0] == ' ')
}

// generatedBlockSchema emits the layout-block paths for each nesting depth.
// Keys are walked in name order so the generated text is stable across builds.
func generatedBlockSchema() string {
	var out strings.Builder
	out.WriteString("\n# Generated by schema.go: layout blocks to blockDepth.\n")
	path := `ui.views.view[*].layout`
	for depth := 1; depth <= blockDepth; depth++ {
		path += `.block[*]`
		fmt.Fprintf(&out, "\nfield: %q\n\ttype: string\n", path)
		for _, key := range slices.Sorted(maps.Keys(blockKeys)) {
			fmt.Fprintf(&out, "field: %q\n\ttype: %s\n", path+"."+key, blockKeys[key])
			if key == "type" {
				fmt.Fprintf(&out, "\tallowed: %s\n", blockTypes)
			}
		}
	}
	return out.String()
}
